openapi: 3.0.3
info:
  version: "latest"
  title: M-Advise
  description: This API provides access to the M-Advise service.
servers:
  - url: "http://localhost:8080"

paths:
  /ping:
    get:
      tags:
        - Health
      summary: Health check
      operationId: ping
      security: []
      description: Check server health
      responses:
        200:
          description: pong
          content:
            text/plain:
              schema:
                type: string
                example: pong
        500:
          $ref: "#/components/responses/500"

  /signin:
    post:
      tags:
        - Security
      summary: Login user.
      operationId: signIn
      security: []
      responses:
        "201":
          description: Logged in payload.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"

  /signup:
    post:
      tags:
        - Security
      summary: Sign up user
      operationId: signUp
      security: []
      requestBody:
        description: Sign up payload.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "201":
          description: Signed up user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"

  /doctors/{id}:
    get:
      tags:
        - User
      summary: Get doctors by identifier
      operationId: getDoctorById
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Required doctor
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Doctor"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"
  /doctors/{id}/patients:
    get:
      tags:
        - User
      summary: Get patients of a specific doctor
      operationId: getPatientsByDoctorId
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of patients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Patient"
        "500":
          $ref: "#/components/responses/500"

  /patients/{id}:
    get:
      tags:
        - User
      summary: Get patient by identifier
      operationId: getPatientById
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Required patient
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Doctor"
        "400":
          $ref: "#/components/responses/400"
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"
        "429":
          $ref: "#/components/responses/429"
        "500":
          $ref: "#/components/responses/500"
  /users/{id}/raw:
    post:
      tags:
        - User
      summary: Update user photo
      operationId: updateProfilePic
      security: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: File key
          content:
            text/plain:
              schema:
                type: string
                example: photo.png
        500:
          $ref: "#/components/responses/500"

  /hospitals:
    get:
      tags:
        - Department
      summary: Get list of hospitals
      operationId: getHospitals
      security: []
      responses:
        200:
          description: List of hospital
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hospital"
        500:
          $ref: "#/components/responses/500"
    put:
      tags:
        - Department
      summary: Crupdate hospital
      operationId: crupdateHospital
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Hospital"
      responses:
        200:
          description: File key
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hospital"
        500:
          $ref: "#/components/responses/500"

  /hospitals/{id}/doctors:
    get:
      tags:
        - Department
      summary: Get list of doctors of a specific hospital
      operationId: getDoctorsByHospitalsId
      parameters:
        - name: id
          schema:
            type: string
          in: path
          required: true
          description: hospital identifier
      security: []
      responses:
        "200":
          description: List of doctors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Doctor"
        "500":
          $ref: "#/components/responses/500"
  /raw/{fileId}:
    post:
      tags:
        - File
      summary: Upload standard file
      operationId: uploadFile
      security: []
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          image/*:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: File key
          content:
            text/plain:
              schema:
                type: string
                example: photo.png
        500:
          $ref: "#/components/responses/500"
    get:
      tags:
        - File
      summary: Retrieve file
      operationId: downloadFile
      security: []
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: The required file
          content:
            image/*:
              schema:
                type: string
                format: binary
        500:
          $ref: "#/components/responses/500"

components:
  responses:
    400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/BadRequestException"
    403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NotAuthorizedException"
    404:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResourceNotFoundException"
    429:
      description: Too many requests to the API
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/TooManyRequestsException"
    500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerException"
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        last_name:
          type: string
        authentication_id:
          type: string
        first_name:
          type: string
        nic:
          type: string
        birth_date:
          type: string
          format: date-time
        email:
          type: string
        photo_id:
          type: string
        role:
          type: string
          enum:
            - ADVISOR
            - DOCTOR
            - PATIENT
    Doctor:
      allOf:
        - $ref: "#/components/schemas/User"
      type: object
      properties:
        hospital_id:
          type: string
        registry_number:
          type: string
    Patient:
      allOf:
        - $ref: "#/components/schemas/User"
      type: object
    Hospital:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        nif:
          type: string
        stat:
          type: string
        contact:
          type: string
        advisor:
          type: object
          properties:
            schemas:
              $ref: "#/components/schemas/User"

    AuthenticationPayload:
      type: object
      properties:
        email:
          type: string
        provider_id:
          type: string

    Page:
      type: integer
      description: Start at `1`
    PageSize:
      type: integer
      description: Cannot exceed `500`
    Exception:
      type: object
      properties:
        type:
          type: string
        message:
          type: string
    BadRequestException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    NotAuthorizedException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    ResourceNotFoundException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    TooManyRequestsException:
      allOf:
        - $ref: "#/components/schemas/Exception"
    InternalServerException:
      allOf:
        - $ref: "#/components/schemas/Exception"
